
# This file is automatically generated, you probably don't want to edit this

hcaOptions <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "hcaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            text = NULL,
            segsize = 40,
            tolower = TRUE,
            stopwords = "english",
            rmvpunct = TRUE,
            lang = "english",
            mintermfreq = 3,
            kmeans = 6,
            minucsize = 10,
            minsplit = 20,
            kgroup = 5,
            plottype = "bar",
            nterms = 20,
            freescales = FALSE,
            measure = "chi2",
            negative = TRUE,
            textsize = 10, ...) {

            super$initialize(
                package='jmvrainette',
                name='hca',
                requiresData=TRUE,
                ...)

            private$..text <- jmvcore::OptionVariable$new(
                "text",
                text)
            private$..segsize <- jmvcore::OptionInteger$new(
                "segsize",
                segsize,
                default=40)
            private$..tolower <- jmvcore::OptionBool$new(
                "tolower",
                tolower,
                default=TRUE)
            private$..stopwords <- jmvcore::OptionList$new(
                "stopwords",
                stopwords,
                options=list(
                    "english",
                    "portuguese"),
                default="english")
            private$..rmvpunct <- jmvcore::OptionBool$new(
                "rmvpunct",
                rmvpunct,
                default=TRUE)
            private$..lang <- jmvcore::OptionList$new(
                "lang",
                lang,
                options=list(
                    "english",
                    "portugues"),
                default="english")
            private$..mintermfreq <- jmvcore::OptionInteger$new(
                "mintermfreq",
                mintermfreq,
                default=3)
            private$..kmeans <- jmvcore::OptionInteger$new(
                "kmeans",
                kmeans,
                default=6)
            private$..minucsize <- jmvcore::OptionInteger$new(
                "minucsize",
                minucsize,
                default=10)
            private$..minsplit <- jmvcore::OptionInteger$new(
                "minsplit",
                minsplit,
                default=20)
            private$..kgroup <- jmvcore::OptionInteger$new(
                "kgroup",
                kgroup,
                default=5)
            private$..plottype <- jmvcore::OptionList$new(
                "plottype",
                plottype,
                options=list(
                    "bar",
                    "cloud"),
                default="bar")
            private$..nterms <- jmvcore::OptionInteger$new(
                "nterms",
                nterms,
                default=20)
            private$..freescales <- jmvcore::OptionBool$new(
                "freescales",
                freescales,
                default=FALSE)
            private$..measure <- jmvcore::OptionList$new(
                "measure",
                measure,
                options=list(
                    "chi2",
                    "lr"),
                default="chi2")
            private$..negative <- jmvcore::OptionBool$new(
                "negative",
                negative,
                default=TRUE)
            private$..textsize <- jmvcore::OptionInteger$new(
                "textsize",
                textsize,
                default=10)

            self$.addOption(private$..text)
            self$.addOption(private$..segsize)
            self$.addOption(private$..tolower)
            self$.addOption(private$..stopwords)
            self$.addOption(private$..rmvpunct)
            self$.addOption(private$..lang)
            self$.addOption(private$..mintermfreq)
            self$.addOption(private$..kmeans)
            self$.addOption(private$..minucsize)
            self$.addOption(private$..minsplit)
            self$.addOption(private$..kgroup)
            self$.addOption(private$..plottype)
            self$.addOption(private$..nterms)
            self$.addOption(private$..freescales)
            self$.addOption(private$..measure)
            self$.addOption(private$..negative)
            self$.addOption(private$..textsize)
        }),
    active = list(
        text = function() private$..text$value,
        segsize = function() private$..segsize$value,
        tolower = function() private$..tolower$value,
        stopwords = function() private$..stopwords$value,
        rmvpunct = function() private$..rmvpunct$value,
        lang = function() private$..lang$value,
        mintermfreq = function() private$..mintermfreq$value,
        kmeans = function() private$..kmeans$value,
        minucsize = function() private$..minucsize$value,
        minsplit = function() private$..minsplit$value,
        kgroup = function() private$..kgroup$value,
        plottype = function() private$..plottype$value,
        nterms = function() private$..nterms$value,
        freescales = function() private$..freescales$value,
        measure = function() private$..measure$value,
        negative = function() private$..negative$value,
        textsize = function() private$..textsize$value),
    private = list(
        ..text = NA,
        ..segsize = NA,
        ..tolower = NA,
        ..stopwords = NA,
        ..rmvpunct = NA,
        ..lang = NA,
        ..mintermfreq = NA,
        ..kmeans = NA,
        ..minucsize = NA,
        ..minsplit = NA,
        ..kgroup = NA,
        ..plottype = NA,
        ..nterms = NA,
        ..freescales = NA,
        ..measure = NA,
        ..negative = NA,
        ..textsize = NA)
)

hcaResults <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Hierarchical Clustering Analysis")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="HCA Plot",
                width=600,
                height=700,
                renderFun=".plot"))}))

hcaBase <- if (requireNamespace('jmvcore', quietly=TRUE)) R6::R6Class(
    "hcaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvrainette',
                name = 'hca',
                version = c(0,1,0),
                options = options,
                results = hcaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Hierarchical Clustering Analysis
#'
#' 
#' @param data .
#' @param text .
#' @param segsize .
#' @param tolower .
#' @param stopwords .
#' @param rmvpunct .
#' @param lang .
#' @param mintermfreq .
#' @param kmeans .
#' @param minucsize .
#' @param minsplit .
#' @param kgroup .
#' @param plottype .
#' @param nterms .
#' @param freescales .
#' @param measure .
#' @param negative .
#' @param textsize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
hca <- function(
    data,
    text,
    segsize = 40,
    tolower = TRUE,
    stopwords = "english",
    rmvpunct = TRUE,
    lang = "english",
    mintermfreq = 3,
    kmeans = 6,
    minucsize = 10,
    minsplit = 20,
    kgroup = 5,
    plottype = "bar",
    nterms = 20,
    freescales = FALSE,
    measure = "chi2",
    negative = TRUE,
    textsize = 10) {

    if ( ! requireNamespace('jmvcore', quietly=TRUE))
        stop('hca requires jmvcore to be installed (restart may be required)')

    if ( ! missing(text)) text <- jmvcore::resolveQuo(jmvcore::enquo(text))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(text), text, NULL))


    options <- hcaOptions$new(
        text = text,
        segsize = segsize,
        tolower = tolower,
        stopwords = stopwords,
        rmvpunct = rmvpunct,
        lang = lang,
        mintermfreq = mintermfreq,
        kmeans = kmeans,
        minucsize = minucsize,
        minsplit = minsplit,
        kgroup = kgroup,
        plottype = plottype,
        nterms = nterms,
        freescales = freescales,
        measure = measure,
        negative = negative,
        textsize = textsize)

    analysis <- hcaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

